import { User, Team, BreakRecord, WCTracking, Warning, SNNHeadline, ShiftConfig, ChatMessage, Broadcast, AuditLogEntry, ShiftNote, Competition } from '../types';

const STORAGE_KEYS = {
  CURRENT_USER: 'bcf_auth_current_user_v3',
  USERS: 'bcf_users_v3',
  TEAMS: 'bcf_teams_v3',
  BREAKS: 'bcf_records_v3',
  WC_TRACKING: 'bcf_wc_tracking_v3',
  WARNINGS: 'bcf_warnings_v3',
  HEADLINES: 'bcf_headlines_v3',
  CONFIG: 'bcf_config_v3',
  MESSAGES: 'bcf_messages_v3',
  BROADCASTS: 'bcf_broadcasts_v3',
  AUDIT_LOGS: 'bcf_audit_logs_v3',
  NOTES: 'bcf_notes_v3',
  COMPETITIONS: 'bcf_competitions_v3',
};

export const INITIAL_TEAMS: Team[] = [
  {
    teamId: 'team_strikers',
    teamName: 'STRIKERS',
    teamLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    teamColorAccent: '#FF003C',
    supervisorEmail: 'tarek.zaki@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 10,
    competitionScore: 1420,
    isActive: true,
  },
  {
    teamId: 'team_titans',
    teamName: 'TITANS',
    teamLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    teamColorAccent: '#00E5FF',
    supervisorEmail: 'rania.fawzy@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 9,
    competitionScore: 1380,
    isActive: true,
  },
  {
    teamId: 'team_apex',
    teamName: 'APEX',
    teamLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    teamColorAccent: '#FFCC00',
    supervisorEmail: 'omar.nabil@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 9,
    competitionScore: 1290,
    isActive: true,
  },
  {
    teamId: 'team_phantom',
    teamName: 'PHANTOM',
    teamLogo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=150&auto=format&fit=crop&q=80',
    teamColorAccent: '#8338EC',
    supervisorEmail: 'dina.helmy@bcflights.com',
    defaultLanguage: 'en',
    agentCount: 8,
    competitionScore: 1210,
    isActive: true,
  },
];

export const INITIAL_USERS: User[] = [
  // Developer Tier 1 (Adham Badran)
  {
    id: 'user_dev_adham',
    name: 'Adham Badran',
    email: 'adhambadraan@gmail.com',
    role: 'developer',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'System Architect & God Mode Overseer ⚡',
    powerEmoji: '⚡',
    podColorTheme: '#FFCC00',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    birthday: '08-15',
    hireDate: '2022-01-01',
    yearsOfService: 4,
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 12,
    totalBreakTime: 95,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 45,
    longestStreak: 45,
    dailyGoal: { text: '100% Floor Uptime & Zero Drift', target: 10, progress: 10, completed: true },
  },
  // Admins Tier 2
  {
    id: 'user_admin_karim',
    name: 'Karim Mansour',
    email: 'karim.admin@bcflights.com',
    role: 'admin',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Keep the revenue closing around the clock 📈',
    powerEmoji: '👑',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 25,
    totalBreakTime: 210,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 30,
    longestStreak: 32,
  },
  {
    id: 'user_admin_maya',
    name: 'Maya Selim',
    email: 'maya.admin@bcflights.com',
    role: 'admin',
    teamId: 'team_titans',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Precision timing, flawless execution 🎯',
    powerEmoji: '💎',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 18,
    totalBreakTime: 160,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 28,
    longestStreak: 28,
  },
  // Supervisors Tier 3
  {
    id: 'user_sup_tarek',
    name: 'Tarek Zaki',
    email: 'tarek.zaki@bcflights.com',
    role: 'supervisor',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'STRIKERS lead the shift every night 🔥',
    powerEmoji: '🔥',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 34,
    totalBreakTime: 320,
    totalWarnings: 0,
    totalBonusReceived: 3,
    currentStreak: 19,
    longestStreak: 22,
  },
  {
    id: 'user_sup_rania',
    name: 'Rania Fawzy',
    email: 'rania.fawzy@bcflights.com',
    role: 'supervisor',
    teamId: 'team_titans',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Titans never break rhythm ⚡',
    powerEmoji: '🛡️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 29,
    totalBreakTime: 290,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 15,
    longestStreak: 18,
  },
  // Agents Tier 4 - Team STRIKERS
  {
    id: 'user_agent_solomon',
    name: 'Solomon Kane',
    email: 'solomon@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Close deals, take 10-min tea breaks ☕',
    powerEmoji: '🚀',
    podColorTheme: '#FF003C',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    birthday: '08-28', // Today! For birthday confetti test
    hireDate: '2023-04-10',
    yearsOfService: 3,
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 45,
    totalBreakTime: 420,
    totalWarnings: 1,
    totalBonusReceived: 8,
    currentStreak: 12,
    longestStreak: 18,
    dailyGoal: { text: '12 Qualified BQ Calls', target: 12, progress: 8, completed: false },
  },
  {
    id: 'user_agent_zayn',
    name: 'Zayn Malik',
    email: 'zayn@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Fast breaks, faster pitches ⚡',
    powerEmoji: '🎯',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 38,
    totalBreakTime: 360,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 21,
    longestStreak: 21,
    dailyGoal: { text: '10 Closed Pipeline Accounts', target: 10, progress: 10, completed: true },
  },
  {
    id: 'user_agent_fabiola',
    name: 'Fabiola Gomez',
    email: 'fabiola@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Top of leaderboard every Friday 🏆',
    powerEmoji: '⭐',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 42,
    totalBreakTime: 390,
    totalWarnings: 0,
    totalBonusReceived: 10,
    currentStreak: 24,
    longestStreak: 30,
    dailyGoal: { text: '15 High-Value Inbound Quotes', target: 15, progress: 12, completed: false },
  },
  {
    id: 'user_agent_leo',
    name: 'Leo Rossi',
    email: 'leo@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'The audacity of great salesmanship 🍕',
    powerEmoji: '🕶️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 50,
    totalBreakTime: 490,
    totalWarnings: 1,
    totalBonusReceived: 3,
    currentStreak: 8,
    longestStreak: 14,
  },
  {
    id: 'user_agent_nora',
    name: 'Nora Al-Sayed',
    email: 'nora@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Patience and persistence pay off 💡',
    powerEmoji: '🌸',
    preferredLanguage: 'ar',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 30,
    totalBreakTime: 280,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 16,
    longestStreak: 16,
  },
  {
    id: 'user_agent_adam',
    name: 'Adam Vance',
    email: 'adam@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Always follow up within 5 minutes ⏱️',
    powerEmoji: '💼',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 36,
    totalBreakTime: 330,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 11,
    longestStreak: 15,
  },
  {
    id: 'user_agent_layla',
    name: 'Layla Hassan',
    email: 'layla@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Night shift warrior 🌙',
    powerEmoji: '🌙',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 33,
    totalBreakTime: 310,
    totalWarnings: 0,
    totalBonusReceived: 6,
    currentStreak: 14,
    longestStreak: 18,
  },
  {
    id: 'user_agent_marcus',
    name: 'Marcus Brody',
    email: 'marcus@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1528892952291-009c663ce843?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Sales is an extreme sport 🏎️',
    powerEmoji: '🏎️',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 40,
    totalBreakTime: 380,
    totalWarnings: 0,
    totalBonusReceived: 5,
    currentStreak: 9,
    longestStreak: 19,
  },
  {
    id: 'user_agent_sara',
    name: 'Sara Chen',
    email: 'sara@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Keep calm and qualify leads ☕',
    powerEmoji: '🍵',
    preferredLanguage: 'en',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 28,
    totalBreakTime: 250,
    totalWarnings: 0,
    totalBonusReceived: 7,
    currentStreak: 20,
    longestStreak: 20,
  },
  {
    id: 'user_agent_youssef',
    name: 'Youssef Tariq',
    email: 'youssef@bcflights.com',
    role: 'agent',
    teamId: 'team_strikers',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=200&auto=format&fit=crop&q=80',
    personalMotto: 'Energy stays at 100% until 6 AM 🔋',
    powerEmoji: '🔋',
    preferredLanguage: 'ar',
    themeMode: 'dark',
    notificationsEnabled: true,
    soundEnabled: true,
    reducedMotion: false,
    reducedTransparency: false,
    fontSize: 'md',
    isOnline: true,
    lastSeen: 'Now',
    totalBreaksTaken: 35,
    totalBreakTime: 340,
    totalWarnings: 0,
    totalBonusReceived: 4,
    currentStreak: 13,
    longestStreak: 17,
  },
];

export const INITIAL_CONFIG: ShiftConfig = {
  breakCapacity: 5,
  maxSlots: 5,
  maxSlotDuration: 15,
  maxTotalBreakTime: 60,
  maxWCTime: 20,
  shiftStartHour: 22,
  shiftEndHour: 6,
  restrictedFirstHour: false, // Set to false during interactive dev demo so user can test punch in immediately
  restrictedLastHour: false,
  restrictedHoursApplyToWC: false,
  masterBreakBlock: false,
  blockedAgents: [],
  maintenanceMode: false,
  maintenanceMessage: 'System undergoing scheduled maintenance. Back online shortly.',
  rallyModeActive: false,
  featuresEnabled: {
    bonusBreaks: true,
    warnings: true,
    ticker: true,
    animations: true,
    messaging: true,
    competitions: true,
    goals: true,
    weather: true,
    birthdays: true,
    leaderboards: true,
  },
  autoWarningThresholds: {
    slotOverrunL1Min: 1,
    slotOverrunL1Max: 3,
    slotOverrunL2Max: 5,
    l1EscalationCount: 3,
    l2EscalationCount: 2,
  },
};

export const INITIAL_HEADLINES: SNNHeadline[] = [
  {
    headlineId: 'hl_1',
    headlineText: 'SOLOMON started a regular break — Slot 2/5',
    category: 'break',
    priority: 'normal',
    relatedAgent: 'solomon@bcflights.com',
    relatedAgentName: 'Solomon Kane',
    teamId: 'team_strikers',
    timestamp: Date.now() - 480000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_2',
    headlineText: 'FABIOLA earned a bonus break for 10+ verified BQ leads! 🍕🎁',
    category: 'bonus',
    priority: 'urgent',
    relatedAgent: 'fabiola@bcflights.com',
    relatedAgentName: 'Fabiola Gomez',
    teamId: 'team_strikers',
    timestamp: Date.now() - 920000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_3',
    headlineText: '🌯 Local: Shawarma prices in Cairo remain rock stable at 3 AM',
    category: 'fun',
    priority: 'normal',
    timestamp: Date.now() - 1500000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_4',
    headlineText: '☕ Investigation: Who drank the last dark roast coffee? Suspects: everyone on shift',
    category: 'fun',
    priority: 'normal',
    timestamp: Date.now() - 2100000,
    visibility: 'all',
  },
  {
    headlineId: 'hl_5',
    headlineText: '👑 STRIKERS maintain #1 floor competition ranking with 1,420 pts',
    category: 'achievement',
    priority: 'urgent',
    timestamp: Date.now() - 3200000,
    visibility: 'all',
  },
];

export const INITIAL_BREAKS: BreakRecord[] = [
  {
    breakId: 'brk_init_1',
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    breakType: 'regular',
    slotNumber: 2,
    startTime: Date.now() - 480000, // 8 minutes ago
    endTime: null,
    duration: 480,
    scheduledEndTime: Date.now() + 420000,
    isActive: true,
    isBonus: false,
    date: new Date().toISOString().split('T')[0],
  },
  {
    breakId: 'brk_init_2',
    agentEmail: 'zayn@bcflights.com',
    agentName: 'Zayn Malik',
    teamId: 'team_strikers',
    breakType: 'wc',
    slotNumber: 1,
    startTime: Date.now() - 320000, // 5 min ago
    endTime: null,
    duration: 320,
    scheduledEndTime: Date.now() + 580000,
    isActive: true,
    isBonus: false,
    date: new Date().toISOString().split('T')[0],
  },
];

export const INITIAL_WC_TRACKING: Record<string, WCTracking> = {
  'solomon@bcflights.com': {
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 420, // 7 min
    wcBreakCount: 1,
    lastWCBreakAt: Date.now() - 7200000,
    hasReceivedLimitWarning: false,
  },
  'zayn@bcflights.com': {
    agentEmail: 'zayn@bcflights.com',
    agentName: 'Zayn Malik',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 320,
    wcBreakCount: 1,
    lastWCBreakAt: Date.now() - 320000,
    hasReceivedLimitWarning: false,
  },
  'leo@bcflights.com': {
    agentEmail: 'leo@bcflights.com',
    agentName: 'Leo Rossi',
    teamId: 'team_strikers',
    date: new Date().toISOString().split('T')[0],
    totalWCTime: 720, // 12 min
    wcBreakCount: 2,
    lastWCBreakAt: Date.now() - 3600000,
    hasReceivedLimitWarning: false,
  },
};

export const INITIAL_WARNINGS: Warning[] = [
  {
    warningId: 'warn_init_1',
    agentEmail: 'solomon@bcflights.com',
    agentName: 'Solomon Kane',
    teamId: 'team_strikers',
    level: 1,
    reason: 'Slot overrun by 2 minutes',
    customNote: 'Hey Solomon, you took 17m on a 15m slot. Level 1 reminder! Keep it clean 😊',
    issuedBy: 'tarek.zaki@bcflights.com',
    issuedByName: 'Tarek Zaki',
    issuedAt: Date.now() - 86400000,
    expiresAt: Date.now() + 259200000,
    cleanShiftsCount: 1,
    requiredCleanShifts: 3,
    status: 'active',
    penalties: { maxBreakTime: 60, maxSlots: 5 },
  },
];

// Helper functions for persistent state
export function getStoredData<T>(key: string, defaultValue: T): T {
  if (typeof window === 'undefined') return defaultValue;
  try {
    const item = localStorage.getItem(key);
    if (!item) {
      localStorage.setItem(key, JSON.stringify(defaultValue));
      return defaultValue;
    }
    return JSON.parse(item);
  } catch {
    return defaultValue;
  }
}

export function setStoredData<T>(key: string, value: T): void {
  if (typeof window === 'undefined') return;
  try {
    localStorage.setItem(key, JSON.stringify(value));
  } catch (e) {
    console.error('Storage write error', e);
  }
}

export { STORAGE_KEYS };
